### PR TITLE
issue #263 - proposed patch

### PR DESCRIPTION
**Pull request by ikarius**
Patched issue #263 - (can't revert 'validatesSecureCertificate' once set to 'NO' on new requests)

### CODE REVIEW

**Comment by greenisus** [comment]
thanks!

**Comment by ikarius** [comment]
You're welcome ! (let's go to sleep now)

Le 5 octobre 2011 19:07, Michael Mayo <
reply@reply.github.com> a
écrit :

> thanks!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pokeb/asi-http-request/pull/264#issuecomment-2300417

## 

Frédéric VERGEZ --
Développeur iOs / Android / Scala
Tél. : +33 981 847 699  - @: fred@ikarius.com

**Comment by shezban** [comment]
Hi 
I am facing the same issue even with v1.8.1-61 2011-09-19, which is having the code fixes as said above in Ref "6600374".
Any solution of this particular issue.

Thanks

**Comment by shezban** [comment]
Issue is, library is not reverting the SSL properties, when user resets validatesSecureCertificate from NO to YES. Though user is saying to perform SSL validation but at OS level, SSL properties are set for not to perform SSL validation [sets when validatesSecureCertificate sets as NO] . Hence library is not giving any error with self-signed certificates and validatesSecureCertificate as YES.

Solution for this is as follows:
- (void)startRequest
  {
  
  ---
  
  //
  // Handle SSL certificate settings
  //
  
  if([[[[self url] scheme] lowercaseString] isEqualToString:@"https"]) {       
  
  ```
  // Tell CFNetwork not to validate SSL certificates
  if (![self validatesSecureCertificate]) {
      // see: http://iphonedevelopment.blogspot.com/2010/05/nsstream-tcp-and-ssl.html
  
      NSDictionary *sslProperties = [[NSDictionary alloc] initWithObjectsAndKeys:
                                [NSNumber numberWithBool:YES], kCFStreamSSLAllowsExpiredCertificates,
                                [NSNumber numberWithBool:YES], kCFStreamSSLAllowsAnyRoot,
                                [NSNumber numberWithBool:NO],  kCFStreamSSLValidatesCertificateChain,
                                kCFNull,kCFStreamSSLPeerName,
                                nil];
  
      CFReadStreamSetProperty((CFReadStreamRef)[self readStream], 
                              kCFStreamPropertySSLSettings, 
                              (CFTypeRef)sslProperties);
      [sslProperties release];
  } 
  ```
  
     /\* Need to add this else loop - Following needs to add to revert back the SSL settings */
      else {
          NSDictionary *sslProperties = [[NSDictionary alloc] initWithObjectsAndKeys:
                                         [NSNumber numberWithBool:NO], kCFStreamSSLAllowsExpiredCertificates,
                                         [NSNumber numberWithBool:NO], kCFStreamSSLAllowsAnyRoot,
                                         [NSNumber numberWithBool:YES],  kCFStreamSSLValidatesCertificateChain,
                                         nil];
  
  ```
      CFReadStreamSetProperty((CFReadStreamRef)[self readStream], 
                              kCFStreamPropertySSLSettings, 
                              (CFTypeRef)sslProperties);
      [sslProperties release];            
  }
  ```
  
  ---

}

Thanks
Shivani

**Pull request merged**
