### PR TITLE
Restored compatibility with OS X 10.5

### PR DESCRIPTION
**Pull request by AriX**

### CODE REVIEW

**Comment by jogu** [comment]
Thanks AriX (apologies for delay in looking at this).

I guess Apple may actually remove this API at some point, so possibly the iOS builds should call the newer API. Not sure though.

**Comment by AriX** [comment]
Sweet! That won't be a problem; only the newer API will ever be used if it's available.

**Comment by jogu** [comment]
Oh... err, yeah. Of course. Clearly wasn't awake when I made that comment! Thanks.

**Comment by AriX** [comment]
Haha, sure.

**Pull request merged**
