### PR TITLE
The ability to set a global user agent

### PR DESCRIPTION
**Pull request by dewski**
The need to set a global user agent for an application can come up, and when there are multiple ASIHTTPRequests it gets cumbersome to have to manually set the User-Agent for each request:

```
[request addRequestHeader:@"User-Agent" value:[NSString stringWithFormat:@"CE API v%@", kCEAPIVersion]];
```

In the commit you'll see its now possible to set a global User-Agent which can still be overwritten on a per request basis. If this was merged, you'll be able to do the following instead:

```
[ASIHTTPRequest setUserAgent:[NSString stringWithFormat:@"CE API v%@", kCEAPIVersion]];
```

### CODE REVIEW

**Comment by pokeb** [comment]
Hi Garret 

Many thanks for the pull request!

You could accomplish something similar by subclassing and overriding defaultUserAgentString. I can see your approach has some advantages, and would make this work the same way as other global properties like defaultTimeOutSeconds.

Unless anyone disagrees, I'll merge this as soon as I get some time.

Best

Ben

**Comment by antonholmquist** [comment]
I agree! Merge and close :)

**Comment by siancu** [comment]
Until this gets merged into the mainline, how can I easily merge this into my fork? (GitHub newb here).

**Comment by atnan** [comment]
@siancu Take a look at hub (https://github.com/defunkt/hub). It let's you do this:

```
git cherry-pick https://github.com/dewski/asi-http-request/commit/dbbb407
```

**Comment by siancu** [comment]
@atnan Many thanks!

**Comment by pokeb** [comment]
Finally merged now, only took 7 months. :)

I've slightly adapted the approach, but the end result is similar.

Thanks again!

Ben

**Pull request closed without merging**
